collections:
  - community.crypto
  - name: community.docker
    version: 3.6.0-b1 # Required for docker-compose v2

roles:
  - geerlingguy.ntp
  - geerlingguy.docker
  - geerlingguy.postgresql
  - jnv.unattended-upgrades
  - jnv.debian-backports # Deprecated but the recommended alternative is even older?
