---
- hosts: 'local'
  become: no
  tags: ['apprise']

  tasks:
    - name: 'Creating the app folder'
      file:
        path: '/home/{{ansible_username}}/apprise'
        state: 'directory'

    - name: 'Creating the config dir with specific perms'
      file:
        path: '/home/{{ansible_username}}/apprise/config'
        state: 'directory'
        mode: '0777'

    - name: 'Copying the docker-compose file'
      include_tasks:
        file: '../tasks/add_docker_app.yaml'
      vars:
        app_name: 'apprise'
        app_port: '3212'
        app_directories: []

    - name: 'Setting-up nginx for Apprise'
      include_tasks:
        file: '../tasks/add_nginx_app.yaml'
      vars:
        app_name: 'apprise'
        app_port: '3212'
        enabled: yes