---
- hosts: 'public'
  tags: ['dns']
  become: yes

  vars:
    homelab: 
      hostname: 'public'
      short_name: '{{domain}}'
      ip: "{{base_ip.split('.')[-1]}}"
      description: 'My public homelab VM'
    homelab_local:
      hostname: "{{hostvars['rubeus-local']['domain']}}"
      short_name: "{{hostvars['rubeus-local']['domain']}}"
      ip: "{{hostvars['rubeus-local']['ansible_host'].split('.')[-1]}}"
      description: 'My local homelab VM'
    minecraft:
      hostname: 'mc'
      short_name: 'mc'
      ip: "{{hostvars['rubeus-mc']['ansible_host'].split('.')[-1]}}"
      description: 'My minecraft server'
    current_machines: "{{ [ homelab, homelab_local, minecraft ] + machines }}"

  tasks:
    - name: 'Install dnsmasq'
      apt:
        name: 'dnsmasq'
        state: 'present'

    - name: 'Config dnsmasq'
      template:
        src: '../templates/dnsmasq.conf.j2'
        dest: '/etc/dnsmasq.conf'

    - name: 'Enable & start the dnsmasq service'
      service:
        name: 'dnsmasq'
        state: 'restarted'
        enabled: yes
