---
- hosts: 'local'
  become: no
  tags: ['jdownloader']

  tasks:
    - name: 'Mount the shares shared folder'
      include_tasks:
        file: '../tasks/add_nas_mount.yaml'
      vars:
        mount_name: 'shares'

    - name: 'Copying the docker-compose file'
      include_tasks:
        file: '../tasks/add_docker_app.yaml'
      vars:
        app_name: 'jdownloader'
        app_directories:
          - 'config'