---
- hosts: 'vps'
  become: no
  tags: ['koel']

  tasks:
    - name: 'Mount the shares shared folder'
      include_tasks:
        file: '../tasks/add_nas_mount.yaml'
      vars:
        mount_name: 'music'

    - name: 'Copying the docker-compose file'
      include_tasks:
        file: '../tasks/add_docker_app.yaml'
      vars:
        app_name: 'koel'
        app_port: '8000'
        app_directories:
          - pg_data
          - search_index