---
- hosts: 'local'
  become: no
  tags: ['manyfold']

  tasks:
    - name: 'Copying the docker-compose file'
      include_tasks:
        file: '../tasks/add_docker_app.yaml'
      vars:
        app_name: 'manyfold'
        app_port: '3214'
        app_directories:
          - 'data'
          - 'db_data'

    - name: 'Setting-up nginx for Gitea'
      include_tasks:
        file: '../tasks/add_nginx_app.yaml'
      vars:
        app_name: 'manyfold'
        app_port: '3214'
        enabled: yes