---
- hosts: 'public'
  become: no
  tags: ['navidrome']

  tasks:
    - name: 'Mount the shares shared folder'
      include_tasks:
        file: '../tasks/add_nas_mount.yaml'
      vars:
        mount_name: 'shares'

    - name: 'Copying the docker-compose file'
      include_tasks:
        file: '../tasks/add_docker_app.yaml'
      vars:
        app_name: 'navidrome'
        app_port: '4533'
        app_directories:
          - data
          - cache

    - name: 'Setting-up nginx for Navidrome'
      include_tasks:
        file: '../tasks/add_nginx_app.yaml'
      vars:
        app_name: 'navidrome'
        app_port: '4533'
        enabled: yes