---
- hosts: 'local'
  become: no
  tags: ['xoa']

  tasks:
    - name: 'Copying the docker-compose file'
      include_tasks:
        file: '../tasks/add_docker_app.yaml'
      vars:
        app_name: 'xoa'
        app_port: '8037'
        app_directories:
          - 'xoa_data'
          - 'redis_data'

    - name: 'Setting-up nginx for Nextcloud'
      include_tasks:
        file: '../tasks/add_nginx_app.yaml'
      vars:
        app_name: 'xoa'
        app_port: '8037'
        enabled: yes