- name: 'Creating the mount folder'
  become: yes
  file:
    path: '/mnt/{{mount_name}}'
    state: 'directory'
    mode: 0777
    owner: '{{ansible_username}}'
    group: '{{ansible_username}}'

- name: 'Mount the mount (and add it to fstab)'
  become: yes
  mount:
    fstype: 'cifs'
    src: '{{smb_mounts[mount_name]["host"]}}'
    path: '/mnt/{{mount_name}}'
    opts: 'username={{smb_mounts[mount_name]["username"]}},password={{smb_mounts[mount_name]["password"]}},uid=1000,gid=1000'
    state: 'mounted'