---
- hosts: "all"
  tags: [ "docker" ]
  become: yes

  tasks:
    - import_role: { name: "geerlingguy.docker" }
      vars:
        docker_edition: "ce"
        docker_users:
          - "{{ ansible_username }}"

    - name: "Enable docker"
      service:
        name: "docker"
        state: "started"
        enabled: yes

    - name: "Create docker apps driver"
      file:
        path: "/opt/docker-apps"
        state: "directory"
        mode: "0755"
        owner: "{{ansible_username}}"
        group: "{{ansible_username}}"
        recurse: yes

    - name: "Create {{item}} dir"
      become: no
      file:
        path: "/opt/docker-apps/{{item.name}}"
        state: "directory"
        mode: "0700"
      loop: "{{ docker_apps }}"

    - name: "Docker files to copy"
      become: no
      copy:
        src: "{{ docker_app.1.src }}"
        dest: "{{ docker_app.1.dest }}"
        mode: "0755"
        owner: "{{ansible_username}}"
        group: "{{ansible_username}}"
      with_subelements:
        - "{{ docker_apps }}"
        - "files_to_copy"
      loop_control:
        loop_var: "docker_app"

    - name: "Create folders for Docker apps"
      become: no
      file:
        path: "{{ docker_app.1 }}"
        state: "directory"
        mode: "0755"
        owner: "{{ansible_username}}"
        group: "{{ansible_username}}"
      with_subelements:
        - "{{ docker_apps }}"
        - "folders_to_create"
      loop_control:
        loop_var: "docker_app"

    - name: "Creating {{item}} docker-compose"
      become: no
      template:
        src: "../templates/docker/{{item.name}}.yaml.j2"
        dest: "/opt/docker-apps/{{item.name}}/docker-compose.yaml"
      loop: "{{ docker_apps }}"

    - name: "Creating scrutiny config"
      become: no
      template:
        src: "../templates/scrutiny_main.yaml.j2"
        dest: "/opt/docker-apps/scrutiny/config/scrutiny.yaml"

    - name: "Starting {{item}}"
      become: no
      community.docker.docker_compose_v2:
        project_src: "/opt/docker-apps/{{item.name}}"
      loop: "{{ docker_apps }}"
